export type DisasterType =
  | "flood"
  | "cyclone"
  | "tsunami"
  | "earthquake"
  | "heatwave"
  | "lightning"
  | "landslide"
  | "wildfire";

export interface DisasterInfo {
  id: DisasterType;
  name: string;
  icon: string;
  shortDescription: string;

  overview: string;

  before: string[];
  during: string[];
  after: string[];

  emergencyKit: string[];

  importantActions: string[];
}

export const disasterData: Record<DisasterType, DisasterInfo> = {
  /* =====================================================
     FLOOD
  ===================================================== */

  flood: {
    id: "flood",
    name: "Flood",
    icon: "🌊",

    shortDescription:
      "Flooding can occur after heavy rainfall, river overflow, storms, or coastal events.",

    overview:
      "Floods occur when water covers land that is normally dry. They can damage homes, roads, infrastructure, and affect access to food, water, and electricity.",

    before: [
      "Keep an emergency kit ready.",
      "Store drinking water and essential medicines.",
      "Keep important documents in a waterproof container.",
      "Know the safest route to higher ground.",
      "Follow local weather and disaster warnings."
    ],

    during: [
      "Move to higher ground if flooding increases.",
      "Avoid walking or driving through floodwater.",
      "Stay away from rivers, drains, and rapidly moving water.",
      "Follow evacuation instructions from authorities.",
      "Switch off electricity if it is safe to do so."
    ],

    after: [
      "Return home only when authorities say it is safe.",
      "Avoid contaminated floodwater.",
      "Stay away from damaged electrical equipment.",
      "Check drinking water before consuming it.",
      "Report damaged infrastructure to authorities."
    ],

    emergencyKit: [
      "Drinking water",
      "First-aid kit",
      "Flashlight",
      "Power bank",
      "Essential medicines",
      "Important documents",
      "Emergency food"
    ],

    importantActions: [
      "Move to higher ground.",
      "Avoid floodwater.",
      "Follow evacuation orders.",
      "Stay informed through official sources."
    ]
  },

  /* =====================================================
     CYCLONE
  ===================================================== */

  cyclone: {
    id: "cyclone",
    name: "Cyclone",
    icon: "🌀",

    shortDescription:
      "Cyclones are powerful storms that can bring strong winds, heavy rainfall, and coastal flooding.",

    overview:
      "Tropical cyclones can cause destructive winds, heavy rainfall, storm surges, flooding, and damage to infrastructure.",

    before: [
      "Monitor official cyclone warnings.",
      "Secure loose objects around your home.",
      "Keep emergency supplies ready.",
      "Charge phones and power banks.",
      "Know your nearest evacuation centre.",
      "Keep important documents protected."
    ],

    during: [
      "Stay indoors and away from windows.",
      "Follow evacuation instructions.",
      "Do not go outside during dangerous conditions.",
      "Avoid flooded roads and coastal areas.",
      "Keep monitoring official updates."
    ],

    after: [
      "Wait for official clearance before leaving shelter.",
      "Avoid fallen power lines.",
      "Stay away from damaged buildings.",
      "Avoid flooded roads.",
      "Report emergencies through appropriate authorities."
    ],

    emergencyKit: [
      "Drinking water",
      "Non-perishable food",
      "Flashlight",
      "Power bank",
      "First-aid kit",
      "Battery-powered radio",
      "Essential medicines"
    ],

    importantActions: [
      "Stay indoors.",
      "Follow evacuation orders.",
      "Avoid coastal and flooded areas.",
      "Monitor official warnings."
    ]
  },

  /* =====================================================
     TSUNAMI
  ===================================================== */

  tsunami: {
    id: "tsunami",
    name: "Tsunami",
    icon: "🌊",

    shortDescription:
      "A tsunami is a series of powerful sea waves that can affect coastal areas.",

    overview:
      "Tsunamis can be generated by undersea earthquakes, volcanic activity, landslides, or other disturbances that displace large amounts of seawater.",

    before: [
      "Know whether you live in a tsunami hazard zone.",
      "Identify evacuation routes to higher ground.",
      "Learn the location of nearby evacuation areas.",
      "Keep an emergency kit ready.",
      "Learn local tsunami warning signals."
    ],

    during: [
      "Move immediately to higher ground or inland if warned.",
      "Stay away from beaches and coastal areas.",
      "Follow official evacuation instructions.",
      "Do not wait to watch the waves.",
      "Stay away from the coast until authorities declare it safe."
    ],

    after: [
      "Do not return to coastal areas until authorities give clearance.",
      "Be prepared for additional waves.",
      "Avoid damaged buildings and infrastructure.",
      "Stay informed through official sources.",
      "Help others only when it is safe to do so."
    ],

    emergencyKit: [
      "Drinking water",
      "First-aid kit",
      "Flashlight",
      "Power bank",
      "Emergency food",
      "Important documents",
      "Essential medicines"
    ],

    importantActions: [
      "Move to higher ground.",
      "Move inland when instructed.",
      "Stay away from beaches.",
      "Follow evacuation orders."
    ]
  },

  /* =====================================================
     EARTHQUAKE
  ===================================================== */

  earthquake: {
    id: "earthquake",
    name: "Earthquake",
    icon: "🌎",

    shortDescription:
      "Earthquakes cause sudden ground shaking and may damage buildings and infrastructure.",

    overview:
      "Earthquakes occur when energy stored in the Earth's crust is suddenly released, producing ground movement.",

    before: [
      "Identify safe areas inside buildings.",
      "Secure heavy furniture and objects.",
      "Keep an emergency kit accessible.",
      "Know emergency exits.",
      "Learn basic earthquake safety procedures."
    ],

    during: [
      "Drop, Cover, and Hold On.",
      "Stay away from windows and glass.",
      "Do not use elevators.",
      "If outdoors, move away from buildings and power lines.",
      "Remain calm and follow official instructions."
    ],

    after: [
      "Check yourself and others for injuries.",
      "Leave damaged buildings carefully.",
      "Watch for aftershocks.",
      "Avoid damaged electrical and gas systems.",
      "Follow official emergency instructions."
    ],

    emergencyKit: [
      "First-aid kit",
      "Drinking water",
      "Flashlight",
      "Power bank",
      "Emergency food",
      "Whistle",
      "Essential medicines"
    ],

    importantActions: [
      "Drop, Cover, and Hold On.",
      "Stay away from windows.",
      "Avoid damaged buildings.",
      "Prepare for aftershocks."
    ]
  },

  /* =====================================================
     HEATWAVE
  ===================================================== */

  heatwave: {
    id: "heatwave",
    name: "Heatwave",
    icon: "🌡️",

    shortDescription:
      "A heatwave is a period of unusually high temperatures that can affect health and daily activities.",

    overview:
      "Extreme heat can cause dehydration, heat exhaustion, heatstroke, and increased risks for vulnerable people.",

    before: [
      "Keep drinking water available.",
      "Plan outdoor activities during cooler hours.",
      "Keep your home as cool as possible.",
      "Check on elderly people and vulnerable individuals.",
      "Monitor official heat warnings."
    ],

    during: [
      "Stay hydrated.",
      "Avoid unnecessary outdoor activity during peak heat.",
      "Stay in cool or shaded places.",
      "Wear lightweight clothing.",
      "Never leave children or pets inside parked vehicles."
    ],

    after: [
      "Continue drinking enough water.",
      "Rest and recover after heat exposure.",
      "Monitor yourself for signs of heat-related illness.",
      "Seek medical assistance if severe symptoms occur."
    ],

    emergencyKit: [
      "Drinking water",
      "Oral rehydration supplies",
      "Light clothing",
      "Sunscreen",
      "Umbrella or hat",
      "Essential medicines"
    ],

    importantActions: [
      "Stay hydrated.",
      "Avoid peak afternoon heat.",
      "Stay in cool areas.",
      "Check on vulnerable people."
    ]
  },

  /* =====================================================
     LIGHTNING
  ===================================================== */

  lightning: {
    id: "lightning",
    name: "Lightning & Thunderstorm",
    icon: "⛈️",

    shortDescription:
      "Thunderstorms can produce lightning, strong winds, heavy rainfall, and dangerous conditions.",

    overview:
      "Lightning can occur during thunderstorms and can cause injuries, fires, and damage to electrical infrastructure.",

    before: [
      "Monitor thunderstorm warnings.",
      "Move indoors when severe weather approaches.",
      "Avoid open fields during thunderstorms.",
      "Secure loose outdoor objects."
    ],

    during: [
      "Stay indoors.",
      "Avoid isolated trees and tall structures.",
      "Stay away from windows.",
      "Avoid unnecessary contact with electrical equipment.",
      "Do not shelter under trees."
    ],

    after: [
      "Stay alert for additional thunderstorms.",
      "Avoid fallen power lines.",
      "Report damaged infrastructure.",
      "Check for injuries and provide help when safe."
    ],

    emergencyKit: [
      "Flashlight",
      "First-aid kit",
      "Power bank",
      "Battery-powered radio",
      "Essential medicines"
    ],

    importantActions: [
      "Move indoors.",
      "Avoid isolated trees.",
      "Stay away from power lines.",
      "Monitor official warnings."
    ]
  },

  /* =====================================================
     LANDSLIDE
  ===================================================== */

  landslide: {
    id: "landslide",
    name: "Landslide",
    icon: "⛰️",

    shortDescription:
      "Landslides occur when soil, rocks, or debris move rapidly down a slope.",

    overview:
      "Heavy rainfall, earthquakes, erosion, and changes to slopes can trigger landslides.",

    before: [
      "Know whether your area is prone to landslides.",
      "Monitor heavy rainfall warnings.",
      "Avoid building near unstable slopes.",
      "Know evacuation routes.",
      "Keep emergency supplies ready."
    ],

    during: [
      "Move away from the path of the landslide.",
      "Evacuate immediately if instructed.",
      "Avoid valleys and low-lying areas near unstable slopes.",
      "Do not cross active landslide zones.",
      "Follow emergency instructions."
    ],

    after: [
      "Stay away from the affected area.",
      "Watch for additional landslides.",
      "Avoid damaged roads and bridges.",
      "Report blocked roads or hazards.",
      "Return only after official clearance."
    ],

    emergencyKit: [
      "First-aid kit",
      "Flashlight",
      "Drinking water",
      "Power bank",
      "Emergency food",
      "Essential medicines"
    ],

    importantActions: [
      "Move away from unstable slopes.",
      "Follow evacuation instructions.",
      "Avoid landslide zones.",
      "Watch for additional movement."
    ]
  },

  /* =====================================================
     WILDFIRE
  ===================================================== */

  wildfire: {
    id: "wildfire",
    name: "Wildfire",
    icon: "🔥",

    shortDescription:
      "Wildfires can spread rapidly through vegetation and may produce dangerous smoke and heat.",

    overview:
      "Wildfires can threaten communities, forests, wildlife, infrastructure, and air quality.",

    before: [
      "Know local evacuation routes.",
      "Keep emergency supplies ready.",
      "Monitor wildfire and weather warnings.",
      "Keep vegetation around buildings managed where appropriate.",
      "Prepare important documents for evacuation."
    ],

    during: [
      "Evacuate when authorities instruct you to do so.",
      "Stay away from active fire zones.",
      "Keep windows and doors closed when smoke is present.",
      "Avoid unnecessary outdoor activity in smoky conditions.",
      "Follow official emergency instructions."
    ],

    after: [
      "Return only after authorities declare the area safe.",
      "Watch for hot spots and damaged structures.",
      "Avoid ash and contaminated areas.",
      "Check air-quality information.",
      "Report hazards to authorities."
    ],

    emergencyKit: [
      "Drinking water",
      "First-aid kit",
      "Flashlight",
      "Power bank",
      "Emergency food",
      "Important documents",
      "Protective mask"
    ],

    importantActions: [
      "Evacuate when instructed.",
      "Stay away from active fires.",
      "Avoid smoke exposure.",
      "Follow official evacuation information."
    ]
  }
};